name: Release

on: [workflow_dispatch]

jobs:
  release:

    runs-on: ubuntu-latest

    container:
      image: openjdk:17-jdk
      options: --user root

    steps:
      - uses: actions/upload-artifact@v4
      - run: |
          chmod +x ./gradlew
          ./gradlew build modPublish --stacktrace
