name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest

    container:
      image: openjdk:17-jdk
      options: --user root

    steps:
      - uses: actions/checkout@v3

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build the mod
        run: ./gradlew build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-artifact
          path: build/libs/*.jar

