name: Release Forge

on: [workflow_dispatch]

jobs:
  releaseForge:

    runs-on: ubuntu-latest

    container:
      image: openjdk:21-jdk
      options: --user root

    steps:
      - uses: actions/checkout@v2.2.0
      - run: |
          chmod +x ./gradlew
          ./gradlew :forge:build forgePublish --stacktrace
